---
- name: Install AWS CloudWatch Agent RPM via dnf
  ansible.builtin.dnf:
    # The amazon-ssm-agent RPM is currently unsigned:
    # https://github.com/aws/amazon-ssm-agent/issues/235
    disable_gpg_check: true
    name:
      - "{{ url }}"

# Note that the corresponding systemd service and timer are copied
# over in main.yml.
- name: Install shell script to attempt to upgrade CloudWatch Agent
  ansible.builtin.copy:
    dest: /usr/local/sbin/upgrade-cloudwatch-agent.sh
    mode: u=rx,g=,o=
    src: upgrade-cloudwatch-agent-rpm.sh
